spring.application.name=forohub
<<<<<<< HEAD
=======
spring.datasource.url=jdbc:mysql://localhost:3306/forohub
spring.datasource.username=root
spring.datasource.password=root123
>>>>>>> 659b459 (Proyecto ForoHub)
